spring:
  application:
    name: beauty
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/salon
    username: salon
    password: 1234
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      indent_output: true
auth:
  jwt:
    secret: oIl6/4nURBUCp7sR40hCUEO82z0VN4CAFbYix6RiReE=
logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework: ERROR
    org.hibernate: TRACE
  file:
    name: myapp.log
    path: C:/Users/meteo/Desktop/beauty
