create table public.masters
(
    id  integer generated by default as identity
        constraint masters_pk
            primary key,
    fio text not null
);

alter table public.masters
    owner to salon;

create table public.services
(
    id    integer generated by default as identity
        constraint services_pk
            primary key,
    name  varchar(255)     not null,
    price double precision not null
);

alter table public.services
    owner to salon;

create table public.master_service
(
    id         integer generated by default as identity
        constraint master_service_pk
            primary key,
    master_id  integer not null
        constraint master_fk
            references public.masters
            on delete cascade,
    service_id integer not null
        constraint service_fk
            references public.services
            on delete cascade
);

alter table public.master_service
    owner to salon;

create table public.time_slots
(
    id         integer generated by default as identity
        constraint time_slots_pk
            primary key,
    time_start time not null,
    time_end   time not null
);

alter table public.time_slots
    owner to salon;

create table public.user_role
(
    id   integer generated by default as identity
        constraint user_role_pk
            primary key,
    name varchar(255) not null
        constraint user_role_pk_2
            unique
);

alter table public.user_role
    owner to salon;

create table public.users
(
    id        integer generated by default as identity
        constraint users_pk
            primary key,
    fio       varchar(255)                                   not null,
    phone     varchar(255)                                   not null
        constraint users_pk_2
            unique,
    password  varchar(255)                                   not null,
    role_name varchar(256) default 'USER'::character varying not null
        constraint role_fk
            references public.user_role (name)
            on delete cascade
);

alter table public.users
    owner to salon;

create table public.records
(
    id           integer generated by default as identity
        constraint records_pk
            primary key,
    date         date    not null,
    time_slot_id integer not null
        constraint time_slot_fk
            references public.time_slots
            on delete cascade,
    master_id    integer not null
        constraint master_fk
            references public.masters
            on delete cascade,
    service_id   integer not null
        constraint servies_fk
            references public.services
            on delete cascade,
    user_id      integer not null
        constraint user_fk
            references public.users
            on delete cascade
);

alter table public.records
    owner to salon;

INSERT INTO user_role(name) values ('ADMIN');

INSERT INTO user_role(name) values ('USER');

INSERT INTO users (fio, phone, password, role_name) VALUES ('Белякова Софья Андреевна', '89872767937', '$2a$10$y16tkC2TkjasFBzLNOhQBOvemogx1woFJ.CIynIrnrbEDIfLsTwee', 'ADMIN');
INSERT INTO time_slots (time_start, time_end) VALUES ('10:00:00', '11:00:00');
INSERT INTO time_slots (time_start, time_end) VALUES ('11:00:00', '12:00:00');
INSERT INTO time_slots (time_start, time_end) VALUES ('12:00:00', '13:00:00');
INSERT INTO time_slots (time_start, time_end) VALUES ('13:00:00', '14:00:00');
INSERT INTO time_slots (time_start, time_end) VALUES ('14:00:00', '15:00:00');
INSERT INTO time_slots (time_start, time_end) VALUES ('15:00:00', '16:00:00');
INSERT INTO time_slots (time_start, time_end) VALUES ('16:00:00', '17:00:00');
INSERT INTO time_slots (time_start, time_end) VALUES ('17:00:00', '18:00:00');
INSERT INTO time_slots (time_start, time_end) VALUES ('18:00:00', '19:00:00');