create table public.masters
(
    id  integer generated by default as identity
        constraint masters_pk
            primary key,
    fio text not null
);

alter table public.masters
    owner to salon;

create table public.services
(
    id    integer generated by default as identity
        constraint services_pk
            primary key,
    name  varchar(255)     not null,
    price double precision not null
);

alter table public.services
    owner to salon;

create table public.master_service
(
    id         integer generated by default as identity
        constraint master_service_pk
            primary key,
    master_id  integer not null
        constraint master_fk
            references public.masters
            on delete cascade,
    service_id integer not null
        constraint service_fk
            references public.services
            on delete cascade
);

alter table public.master_service
    owner to salon;

create table public.time_slots
(
    id         integer generated by default as identity
        constraint time_slots_pk
            primary key,
    time_start time not null,
    time_end   time not null
);

alter table public.time_slots
    owner to salon;

create table public.user_role
(
    id   integer generated by default as identity
        constraint user_role_pk
            primary key,
    name varchar(255) not null
        constraint user_role_pk_2
            unique
);

alter table public.user_role
    owner to salon;

create table public.users
(
    id        integer generated by default as identity
        constraint users_pk
            primary key,
    fio       varchar(255)                                   not null,
    phone     varchar(255)                                   not null
        constraint users_pk_2
            unique,
    password  varchar(255)                                   not null,
    role_name varchar(256) default 'USER'::character varying not null
        constraint role_fk
            references public.user_role (name)
            on delete cascade,
    role      bytea
);

alter table public.users
    owner to salon;

create table public.records
(
    id           integer generated by default as identity
        constraint records_pk
            primary key,
    date         date    not null,
    time_slot_id integer not null
        constraint time_slot_fk
            references public.time_slots
            on delete cascade,
    master_id    integer not null
        constraint master_fk
            references public.masters
            on delete cascade,
    service_id   integer not null
        constraint servies_fk
            references public.services
            on delete cascade,
    user_id      integer not null
        constraint user_fk
            references public.users
            on delete cascade
);

alter table public.records
    owner to salon;

